name: DeathSwap
version: '1.2'
main: net.fliuxx.deathSwap.DeathSwap
api-version: '1.20'
description: "Costruisci trappole per soprendere e uccidere i player con cui verrai swappato!"
author: "Fl1uxxNoob"
commands:
  dsw:
    description: "Comandi per la DeathSwap"
    aliases: [deathswap]
    usage: "/dsw <start|stop|gui|credits|spectate|spawn>"
permissions:
  deathswap.admin.start:
    description: "Permesso per avviare la DeathSwap."
    default: op
  deathswap.admin.stop:
    description: "Permesso per fermare la DeathSwap."
    default: op
  deathswap.admin.gui:
    description: "Permesso per aprire la GUI di configurazione."
    default: op

